### PR TITLE
Fill out PlatformFile API with more functionality

### PR DESCRIPTION
**Pull request by zacharee**

### CODE REVIEW

**Comment by vinceglb** [comment]
Thank you so much for your work!

I really appreciate the idea of having all these convenient methods available from `IPlatformFile`. The developer has every tool he expects to have from a file. At the same time, it seems to add the streaming feature asked in this issue: https://github.com/vinceglb/FileKit/issues/54.

Here are some questions / notes I have:
- There are some methods that are not supported on some platforms. For example `setReadOnly`, `setWritable`, `setReadable` methods are only working on the `PlatformFile` from jvmAndAndroid target. As FileKit maintainer, how do we deal with that? Do we let developers figure it out by themselves that some methods are working on some targets, some are not? If not supported, do we throw exceptions or just return null? If some methods are only working on only one target, do we still want to support them in FileKit?
- There is now a `PlatformFile` shared between Android and JVM target. But for now, it is never used in the Android target. Instead of it, `PlatformUriFile` is used. What are the benefits of having those two options for the Android target?
- I launched the SampleCompose Wasm application. I noticed the images I selected didn't display properly, and the download feature crashes the app.
- Do you think adding convenient methods on `PlatformFile` working on all targets like accessing bytes and saving bytes are good things? The idea is to keep common tasks easy to use across different platforms.

**Comment by zacharee** [comment]
This is a bit of an experiment, and it still needs a lot of work, which is why I kept it in a draft state.

I think the web target file handling might be fundamentally incompatible with how other platforms do it (iOS, Android, Java, Node), so maybe it would be best not to have a fully-featured PlatformFile in FileKit.

**Comment by zacharee** [comment]
I decided to make a dedicated library for a PlatformFile implementation that just doesn't target JS/Wasm: https://github.com/zacharee/KMPFile. I also added in missing function implementations for Apple (untested). Next step is looking into publishing to Maven.

**Comment by zacharee** [comment]
KMPFile is on Maven Central now, with an additional module that adds convenience functions for converting from FileKit files.

@vinceglb do you think it makes sense to link KMPFile from the README here for people who want more advanced cross-platform file management? No problem if not, of course.

**Comment by vinceglb** [comment]
@zacharee That's really cool! I really appreciate the extensions you've created to plug KMPFile to FileKit! I'm going to update the readme with your library 👌 

It's true when you said that the web target is fundamentally different from other targets. I'm going to see if there are better ways to handle file saving and file management in the future, including (or not ?) the web target.

Anyway, thanks for your time 🙏

**Comment by vinceglb** [comment]
@zacharee That's live 👌 

https://github.com/vinceglb/FileKit?tab=readme-ov-file#-going-further-with-files

**Pull request closed without merging**
